TAG : 'Program:MainProgram.ProdCount.ACC'
PLC_IP : '10.4.43.103'

devices:
  - name: test-pylogix
    frequency: 1
    driver: pylogix
    ip: '10.4.43.103'
    slot: 0           # optional

    tags:
      - type: ping
        name: 'test-ping'
        tag: 'Program:MainProgram.ProdCount.ACC'
        frequency: 5 # optional

      - type: conter
        name: 'test-count'  # name for data point
        tag: 'Program:MainProgram.ProdCount.ACC'  # PLC tag name
        machine: 1530       # machine number for database entry
        scale: 1            # number of parts made per cycle

        # to get the part type, specify either:
        # a part_number_text tag
        part_number_text: 'Program:MainProgram.ProdCountpartText' 
        # or an index tag and the part_dict
        part_number_index: 'Program:MainProgram.ProdCountpartDINT'
        part_dict:
          0: '50-0455'
          1: '50-9341'

        frequency: 5        # optional, defaults to device freq
